"""add progress field to campaign tabledocker

Revision ID: 0e0d0630b3bf
Revises: 72c0e73f4cba
Create Date: 2024-11-17 23:30:24.946356

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e0d0630b3bf"
down_revision: Union[str, None] = "72c0e73f4cba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaign", sa.Column("progress", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaign", "progress")
    # ### end Alembic commands ###
