"""add campaign donations and feedpost relationsdocker

Revision ID: 72c0e73f4cba
Revises:
Create Date: 2024-11-17 01:28:37.970215

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "72c0e73f4cba"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign",
        sa.Column("creator_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("header_img", sa.LargeBinary(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("story", sa.String(), nullable=False),
        sa.Column("goal", sa.BigInteger(), nullable=False),
        sa.Column("amt_reached", sa.BigInteger(), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column(
            "category", postgresql.ARRAY(sa.String(), zero_indexes=True), nullable=False
        ),
        sa.Column(
            "social_media_links",
            postgresql.ARRAY(sa.String(), zero_indexes=True),
            nullable=False,
        ),
        sa.Column("no_of_supporters", sa.Integer(), nullable=False),
        sa.Column("no_of_reactions", sa.Integer(), nullable=False),
        sa.Column("beneficiary_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["beneficiary_user_id"],
            ["users.id"],
            name=op.f("campaign_beneficiary_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("campaign_creator_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("campaign_pkey")),
    )
    op.create_table(
        "donation",
        sa.Column("anonymous", sa.Boolean(), nullable=False),
        sa.Column("payaza_reference", sa.String(), nullable=False),
        sa.Column("transaction_reference", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "social_media_link",
            postgresql.ARRAY(sa.String(), zero_indexes=True),
            nullable=True,
        ),
        sa.Column("donor_id", sa.Uuid(), nullable=True),
        sa.Column("recovery_acct_no", sa.Integer(), nullable=False),
        sa.Column("recovery_acct_bank", sa.String(), nullable=False),
        sa.Column("recovery_acct_name", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("donation_campaign_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["donor_id"],
            ["users.id"],
            name=op.f("donation_donor_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("donation_pkey")),
    )
    op.create_table(
        "feedpost",
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "media",
            postgresql.ARRAY(sa.LargeBinary(), zero_indexes=True),
            nullable=True,
        ),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("no_of_reactions", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("feedpost_campaign_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("feedpost_creator_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("feedpost_pkey")),
    )
    op.create_table(
        "user_campaign_reaction",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name=op.f("user_campaign_reaction_campaign_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_campaign_reaction_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_campaign_reaction_pkey")),
    )
    op.create_table(
        "user_feed_post_reaction",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("feed_post_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feed_post_id"],
            ["feedpost.id"],
            name=op.f("user_feed_post_reaction_feed_post_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_feed_post_reaction_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_feed_post_reaction_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_feed_post_reaction")
    op.drop_table("user_campaign_reaction")
    op.drop_table("feedpost")
    op.drop_table("donation")
    op.drop_table("campaign")
    # ### end Alembic commands ###
