name: Lint

on: [push, pull_request]

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, '--no-ci')"
    name: Run linters
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          pip install -r requirements/dev.txt
      - name: Lint with ruff
        run: |
          ruff check --output-format=github .
      - name: Format with ruff
        run: |
          ruff format . --check
      - name: Type check with pyright
        run: |
          pyright
